services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - '8080:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    command: sh -c "if [ ! -x node_modules/.bin/nodemon ]; then npm install; fi && npm run dev -- --legacy-watch"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    restart: always
    env_file: 
      - '.env'
    depends_on:
      - redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    command: sh -c "if [ ! -x node_modules/.bin/nodemon ]; then npm install; fi && npm run dev -- --legacy-watch"
    volumes:
      - ./worker:/app
      - worker_node_modules:/app/node_modules
    restart: always
    env_file: 
      - '.env'
    depends_on:
      - redis
      - postgres
  redis:
    image: redis
    volumes: 
      - /tmp/redis/data:/data
    restart: always
    ports:
      - 6379:6379
  postgres:
    image: postgres
    volumes: 
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    ports: 
      - 5432:5432
    env_file:
      - 'db.env'

volumes:
  api_node_modules:
  worker_node_modules: